name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore Core.slnf

    - name: Build
      run: dotnet build --no-restore Core.slnf -p:Version=${{ format('0.5.{0}', github.run_number) }}

    - name: Pack
      run: dotnet pack --include-symbols --include-source --no-build -p:Version=${{ format('0.5.{0}', github.run_number) }} -p:SymbolPackageFormat=snupkg -o dist

    - name: Archive nuget source
      uses: actions/upload-artifact@v3
      with:
        name: testout-packages
        path: dist
